"""Update schema

Revision ID: b7f223563c98
Revises: f4c94de78820
Create Date: 2024-09-21 21:24:22.478291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f223563c98'
down_revision: Union[str, None] = 'f4c94de78820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problems', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('problems', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('problems', 'client',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('problems', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('relationships', 'from_segment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('relationships', 'to_segment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('relationships', 'relationship_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('segments', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('segments', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('segments', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('segments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('segments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('segments', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('segments', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('segments', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('relationships', 'relationship_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('relationships', 'to_segment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('relationships', 'from_segment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('problems', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('problems', 'client',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('problems', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('problems', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
